import { ObjectId } from 'mongodb';

/**
 * Represents a daily exercise activity log entry
 * Based on the schema defined in database-schema.md
 */
export interface ExerciseActivityLog {
  _id: ObjectId;
  userId: ObjectId;       // Reference to users._id
  exerciseId: ObjectId;   // Reference to exercises._id
  planId: ObjectId;       // Reference to trainingPlans._id
  weekNumber: number;     // Which week of the plan
  date: Date;             // When this activity was performed
  setsCompleted: number;  // Integer
  repsCompleted: string[];  // Array of strings (e.g., ["10", "8", "8"])
  weight?: string;        // Optional, e.g., "10kg", "Bodyweight"
  durationSeconds?: number; // Optional, Integer
  notes?: string;         // Optional
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Type for creating a new exercise activity log document
 * Omits the _id field which is generated by MongoDB
 */
export type ExerciseActivityLogCreate = Omit<ExerciseActivityLog, '_id'>;

/**
 * Type for updating an exercise activity log document
 * All fields are optional except updatedAt
 */
export type ExerciseActivityLogUpdate = Partial<Omit<ExerciseActivityLog, '_id' | 'userId' | 'exerciseId' | 'planId' | 'createdAt'>> & {
  updatedAt: Date;
};

/**
 * Represents a filter for querying exercise activity logs
 */
export interface ExerciseActivityLogFilter {
  _id?: ObjectId;
  userId?: ObjectId;
  exerciseId?: ObjectId;
  planId?: ObjectId;
  weekNumber?: number;
  date?: { $gte?: Date, $lte?: Date };
} 