import { ObjectId } from 'mongodb';

/**
 * Represents a user-created training plan
 * Based on the schema defined in database-schema.md
 */
export interface TrainingPlan {
  _id: ObjectId;
  userId: ObjectId;     // Reference to users._id, Indexed
  name: string;
  durationWeeks: number; // Integer
  isActive: boolean;    // Default: false, Indexed (with partial unique index)
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Type for creating a new training plan document
 * Omits the _id field which is generated by MongoDB
 */
export type TrainingPlanCreate = Omit<TrainingPlan, '_id'>;

/**
 * Type for updating a training plan document
 * All fields are optional except updatedAt
 */
export type TrainingPlanUpdate = Partial<Omit<TrainingPlan, '_id' | 'userId' | 'createdAt'>> & {
  updatedAt: Date;
};

/**
 * Represents a filter for querying training plans
 */
export interface TrainingPlanFilter {
  _id?: ObjectId;
  userId?: ObjectId;
  isActive?: boolean;
  name?: string | RegExp;
} 