import { ObjectId } from 'mongodb';

/**
 * Represents the canonical definition of an exercise type
 * Based on the schema defined in database-schema.md
 */
export interface ExerciseDefinition {
  _id: ObjectId;
  userId?: ObjectId | null;    // Optional: null = global exercise, non-null = user-specific custom exercise
  name: string;                // Indexed, Unique (e.g., "Bench Press")
  imageUrl: string;
  primaryMuscle: string;       // Primary muscle targeted
  secondaryMuscles: string[];  // Array of secondary muscles targeted
  bodyWeight: boolean;         // Whether it's a bodyweight exercise
  type: string;                // Exercise category/type
  static: boolean;             // Whether the exercise is static (e.g., a plank)
  createdAt?: Date;            // Optional for backward compatibility
  updatedAt?: Date;            // Optional for backward compatibility
}

/**
 * Type for creating a new exercise definition document
 * Omits the _id field which is generated by MongoDB
 * Timestamps are required for new entries
 */
export type ExerciseDefinitionCreate = Omit<ExerciseDefinition, '_id'> & {
  createdAt: Date;
  updatedAt: Date;
};

/**
 * Type for updating an exercise definition document
 * All fields are optional except updatedAt
 */
export type ExerciseDefinitionUpdate = Partial<Omit<ExerciseDefinition, '_id' | 'createdAt'>> & {
  updatedAt: Date;
};

/**
 * Represents a filter for querying exercise definitions
 */
export interface ExerciseDefinitionFilter {
  _id?: ObjectId;
  userId?: ObjectId | null;
  name?: string | RegExp;
  primaryMuscle?: string;
  type?: string;
  bodyWeight?: boolean;
} 