import { ObjectId } from 'mongodb';

/**
 * Represents a saved workout template
 * Based on the schema defined in database-schema.md
 */
export interface SavedWorkout {
  _id: ObjectId;
  userId: ObjectId;    // Reference to users._id
  name: string;
  description?: string; // Optional
  exercises: SavedWorkoutExercise[];
  tags?: string[];     // Optional array of tags
  createdAt: Date;
  updatedAt: Date;
  planId: ObjectId;
}

/**
 * Represents an exercise within a saved workout
 */
export interface SavedWorkoutExercise {
  definitionId: ObjectId; // Reference to exerciseDefinitions._id
  sets: number;           // Integer
  reps: string;           // e.g., "12", "8-12", "AMRAP"
  weight?: string;        // Optional, e.g., "10kg", "Bodyweight"
  durationSeconds?: number; // Optional, Integer
  notes?: string;         // Optional
  order: number;          // Integer
}

/**
 * Type for creating a new saved workout document
 * Omits the _id field which is generated by MongoDB
 */
export type SavedWorkoutCreate = Omit<SavedWorkout, '_id'>;

/**
 * Type for updating a saved workout document
 * All fields are optional except updatedAt
 */
export type SavedWorkoutUpdate = Partial<Omit<SavedWorkout, '_id' | 'userId' | 'createdAt'>> & {
  updatedAt: Date;
};

/**
 * Represents a filter for querying saved workouts
 */
export interface SavedWorkoutFilter {
  _id?: ObjectId;
  userId?: ObjectId;
  name?: string | RegExp;
  tags?: { $in: string[] };
  planId?: ObjectId;
} 